version: '3'

services:
  fastapi:
    build:
      context: ../../
      dockerfile: code/deployment/api/Dockerfile
    container_name: fastapi
    ports:
      - "80:80"

  streamlit:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: streamlit
    ports:
      - "8501:8501"
    depends_on:
      - fastapi